# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0003_loginpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='LoginPage',
        ),
    ]
